import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { MessagesProvider } from "@/context/MessagesContext";
import { UserDetailsProvider } from "@/context/UserDetailsContext";
import { Toaster } from "@/components/ui/sonner";
import { AIModelProvider } from "@/context/AIModelContext";

const latoFont = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // Adjust weights as needed
});

export const metadata: Metadata = {
  title: "WeiverAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${latoFont.variable} antialiased`}>
        <UserDetailsProvider>
          <AIModelProvider>
            <MessagesProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
              >
                {children}
                <Toaster richColors />
              </ThemeProvider>
            </MessagesProvider>
          </AIModelProvider>
        </UserDetailsProvider>
      </body>
    </html>
  );
}
